// Central Socket.IO event names (admin frontend)

export const SOCKET_EVENTS = Object.freeze({
  COMMISSION_UPDATED: 'COMMISSION_UPDATED',
  PAYOUT_UPDATED: 'PAYOUT_UPDATED',
  PAYOUT_HISTORY_UPDATED: 'PAYOUT_HISTORY_UPDATED',
  PARTNER_EARNINGS_UPDATED: 'PARTNER_EARNINGS_UPDATED',
  PARTNER_PAYMENT_STATUS_UPDATED: 'PARTNER_PAYMENT_STATUS_UPDATED',
  ADMIN_ANALYTICS_UPDATED: 'ADMIN_ANALYTICS_UPDATED',
});
